# Generated by Django 4.2.27 on 2025-12-13 03:46

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "user_id",
                    models.BigAutoField(
                        primary_key=True, serialize=False, verbose_name="ユーザーID"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="ログインに使用するメールアドレス",
                        max_length=255,
                        unique=True,
                        verbose_name="メールアドレス",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="ユーザー名")),
                (
                    "icon_url",
                    models.URLField(
                        blank=True,
                        help_text="プロフィール画像のURL",
                        max_length=500,
                        null=True,
                        verbose_name="アイコンURL",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="有効フラグ"),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="管理画面へのアクセス権限",
                        verbose_name="スタッフフラグ",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "ユーザー",
                "verbose_name_plural": "ユーザー",
                "db_table": "users",
            },
        ),
    ]
