# Generated by Django 4.2.27 on 2025-12-12 15:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProblemGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="タイトル")),
                ("description", models.TextField(verbose_name="説明")),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("easy", "Easy"),
                            ("medium", "Medium"),
                            ("hard", "Hard"),
                        ],
                        max_length=10,
                        verbose_name="難易度",
                    ),
                ),
                (
                    "app_scale",
                    models.CharField(
                        choices=[
                            ("small", "Small"),
                            ("medium", "Medium"),
                            ("large", "Large"),
                        ],
                        max_length=10,
                        verbose_name="アプリ規模",
                    ),
                ),
                (
                    "mode",
                    models.CharField(
                        choices=[
                            ("db_only", "DB Only"),
                            ("api_only", "API Only"),
                            ("both", "Both"),
                        ],
                        max_length=10,
                        verbose_name="モード",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "created_by_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="problem_groups",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="作成者",
                    ),
                ),
            ],
            options={
                "verbose_name": "問題グループ",
                "verbose_name_plural": "問題グループ",
                "db_table": "problem_groups",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Problem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "problem_type",
                    models.CharField(
                        choices=[("db", "DB Design"), ("api", "API Design")],
                        max_length=10,
                        verbose_name="問題タイプ",
                    ),
                ),
                ("order_index", models.PositiveIntegerField(verbose_name="問題順序")),
                ("problem_body", models.TextField(verbose_name="問題本文")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "problem_group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="problems",
                        to="problems.problemgroup",
                        verbose_name="問題グループ",
                    ),
                ),
            ],
            options={
                "verbose_name": "問題",
                "verbose_name_plural": "問題",
                "db_table": "problems",
                "ordering": ["problem_group", "order_index"],
                "unique_together": {("problem_group", "order_index")},
            },
        ),
    ]
