# Generated by Django 4.2.27 on 2025-12-13 07:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("problems", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Answer",
            fields=[
                (
                    "answer_id",
                    models.BigAutoField(
                        primary_key=True, serialize=False, verbose_name="回答ID"
                    ),
                ),
                ("answer_body", models.TextField(verbose_name="回答本文")),
                (
                    "grade",
                    models.IntegerField(
                        choices=[(0, "×"), (1, "△"), (2, "○")],
                        help_text="0:×, 1:△, 2:○",
                        verbose_name="採点結果",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "problem",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="problems.problem",
                        verbose_name="問題",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="ユーザー",
                    ),
                ),
            ],
            options={
                "verbose_name": "回答",
                "verbose_name_plural": "回答",
                "db_table": "answers",
                "ordering": ["-created_at"],
            },
        ),
    ]
