# Generated by Django 4.2.27 on 2025-12-13 16:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("problems", "0003_rename_primary_keys"),
    ]

    operations = [
        migrations.AlterField(
            model_name="problem",
            name="problem_id",
            field=models.BigAutoField(
                primary_key=True, serialize=False, verbose_name="問題ID"
            ),
        ),
        migrations.AlterField(
            model_name="problemgroup",
            name="problem_group_id",
            field=models.BigAutoField(
                primary_key=True, serialize=False, verbose_name="問題グループID"
            ),
        ),
    ]
