# Generated by Django 4.2.27 on 2026-03-23 18:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("problems", "0006_add_missing_models"),
    ]

    operations = [
        migrations.CreateModel(
            name="PersonalizedModelAnswer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        primary_key=True, serialize=False, verbose_name="個別模範解答ID"
                    ),
                ),
                ("version", models.PositiveIntegerField(verbose_name="バージョン")),
                ("model_answer", models.TextField(verbose_name="模範解答")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
            ],
            options={
                "verbose_name": "個別模範解答",
                "verbose_name_plural": "個別模範解答",
                "db_table": "personalized_model_answers",
                "ordering": ["problem", "user", "version"],
            },
        ),
        migrations.CreateModel(
            name="RequirementItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        primary_key=True, serialize=False, verbose_name="追加要件ID"
                    ),
                ),
                (
                    "subject",
                    models.CharField(
                        help_text="例: posts, users",
                        max_length=255,
                        verbose_name="対象",
                    ),
                ),
                (
                    "predicate",
                    models.CharField(
                        help_text="例: delete_policy, max_length",
                        max_length=255,
                        verbose_name="項目名",
                    ),
                ),
                (
                    "object_value",
                    models.CharField(
                        help_text="例: soft_delete",
                        max_length=255,
                        verbose_name="決定値",
                    ),
                ),
                (
                    "detail_text",
                    models.TextField(
                        help_text="追加要件を自然文で表した説明", verbose_name="詳細"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
            ],
            options={
                "verbose_name": "追加要件",
                "verbose_name_plural": "追加要件",
                "db_table": "requirement_items",
                "ordering": ["problem_group", "user", "requirement_turn_log", "id"],
            },
        ),
        migrations.CreateModel(
            name="RequirementTurnLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        primary_key=True, serialize=False, verbose_name="要件対話ログID"
                    ),
                ),
                ("user_question", models.TextField(verbose_name="ユーザー質問")),
                ("ai_answer", models.TextField(verbose_name="AI回答")),
                ("turn_no", models.PositiveIntegerField(verbose_name="ターン番号")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
            ],
            options={
                "verbose_name": "要件対話ログ",
                "verbose_name_plural": "要件対話ログ",
                "db_table": "requirement_turn_logs",
                "ordering": ["problem_group", "user", "turn_no"],
            },
        ),
        migrations.AlterUniqueTogether(
            name="problem",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="answer",
            constraint=models.CheckConstraint(
                check=models.Q(("grade__in", [0, 1, 2])), name="answers_grade_valid"
            ),
        ),
        migrations.AddConstraint(
            model_name="problem",
            constraint=models.UniqueConstraint(
                fields=("problem_group", "order_index"),
                name="problems_group_order_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="problem",
            constraint=models.CheckConstraint(
                check=models.Q(("problem_type__in", ["db", "api"])),
                name="problems_problem_type_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="problemgroup",
            constraint=models.CheckConstraint(
                check=models.Q(("difficulty__in", ["easy", "medium", "hard"])),
                name="problem_groups_difficulty_valid",
            ),
        ),
        migrations.AddField(
            model_name="requirementturnlog",
            name="problem_group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="requirement_turn_logs",
                to="problems.problemgroup",
                verbose_name="問題グループ",
            ),
        ),
        migrations.AddField(
            model_name="requirementturnlog",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="requirement_turn_logs",
                to=settings.AUTH_USER_MODEL,
                verbose_name="ユーザー",
            ),
        ),
        migrations.AddField(
            model_name="requirementitem",
            name="problem_group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="requirement_items",
                to="problems.problemgroup",
                verbose_name="問題グループ",
            ),
        ),
        migrations.AddField(
            model_name="requirementitem",
            name="requirement_turn_log",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="requirement_items",
                to="problems.requirementturnlog",
                verbose_name="要件対話ログ",
            ),
        ),
        migrations.AddField(
            model_name="requirementitem",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="requirement_items",
                to=settings.AUTH_USER_MODEL,
                verbose_name="ユーザー",
            ),
        ),
        migrations.AddField(
            model_name="personalizedmodelanswer",
            name="problem",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="personalized_model_answers",
                to="problems.problem",
                verbose_name="問題",
            ),
        ),
        migrations.AddField(
            model_name="personalizedmodelanswer",
            name="problem_group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="personalized_model_answers",
                to="problems.problemgroup",
                verbose_name="問題グループ",
            ),
        ),
        migrations.AddField(
            model_name="personalizedmodelanswer",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="personalized_model_answers",
                to=settings.AUTH_USER_MODEL,
                verbose_name="ユーザー",
            ),
        ),
        migrations.AddConstraint(
            model_name="requirementturnlog",
            constraint=models.UniqueConstraint(
                fields=("problem_group", "user", "turn_no"),
                name="requirement_turn_logs_group_user_turn_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="personalizedmodelanswer",
            constraint=models.UniqueConstraint(
                fields=("problem", "problem_group", "user", "version"),
                name="personalized_model_answers_unique",
            ),
        ),
    ]
